### ISSUE TITLE
Take picture command

### ISSUE THREAD

**Issue by haroldteng** [laksh22/MDP#94]
Hey, may I ask which part of the algorithm code consists of the take picture command that is being sent to the Rpi as described under the Object Detection readme, point 1. 

"**Whenever RPi receives a take picture command from TCP @r_x_y_orientation!.** The coordinates and orientation will be saved as a file in a folder (coords_orien) with filename (x_y_orientation). The file will have no contents."

**Comment by voonhous** [comment]
Hello @haroldteng, I'm not in the algorithm team, but I can help shed some light as to how the algorithm code is being implemented for taking a picture. 

**High level overview :**
1. You will need to know how your camera is mounted. i.e. Where it is facing. It can be facing towards the left/right.
2. The algorithm will only be sending a take picture command when there is an obstacle detected (from the sensor values), as such, you will not need to waste time taking pictures for every single movement.
3. The algorithm will only proceed with the next action after an `ACK` has been received by the image taking handler. This is ensure that the robot is completely stationary while the picture is being taken. (This shouldn't take too long with the current image taking implementation, but the delay is somewhat visible. In our experience, the round trip time is around .6 seconds).
4. Building on top of point 3. You will probably need to have some sort of error handling to handle the case where an `ACK` is not received within a period of time. In such a case, you can try to resend the take picture command.

**Note :**
1. In our implementation, the camera is facing rightwards. 
2. Please use the `[mjpg_streamer.py](https://github.com/laksh22/MDP/blob/master/Object%20Detection/RPi/mjpg_streamer.py)` streamer to adjust the FoV of your camera accordingly. After starting the script on your Raspberry Pi (make sure that you have the required dependencies installed), head to https://ip_of_you_rpi:8000 to get the point of view of the camera that you have mounted.

I'll leave it to the algorithm team to chime in on where you can find the exact implementation.

**Comment by haroldteng** [comment]
Thanks so much for your explanation!

**Comment by voonhous** [comment]
@haroldteng The code for controlling photo taking is not uploaded into this repo. No one in the group has the actual implementation used.

Feel free to submit a PR should you actually want to take on the challenge to implement it yourself.

**Comment by voonhous** [comment]
@haroldteng 

We manage to find and restore the take picture command implementation. 

The PR has been submitted and is awaiting Algorithm team's approval.

**Comment by haroldteng** [comment]
@voonhous wow amazing!:) Sorry for the inconvenience caused.

**Comment by voonhous** [comment]
The PR has been merged into master, issue of: `Missing take picture implementation command" is hence resolved`.
